#!/usr/bin/env bash

set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \n'

readonly DAY_SECONDS=86400

# ------------------------------------------------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------------------------------------------------

emit_day() {
	local day_index=$1
	local option=$2
	local today=$3

	local content
	local title
	local word

	title=$(date -d "@$((today - DAY_SECONDS * day_index))" +%Y-%m-%d)
	word=$(date -d "$title" +%A)
	content=$(grep "$title" "$DONE_FILE" || true)

	if [[ -z $content && $option == -o ]]; then
		return
	fi

	echo "=========================="
	echo "$word : $title"
	echo "=========================="
	echo "$content"
}

# ------------------------------------------------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------------------------------------------------

usage() {
	cat <<-EOF
	XP - A todo.sh module designed to print a readable guide of what you've accomplished in any number of days.

	Usage:
	  todo.sh xp [-oh] days

	Options:
	  -o  Omit days on which no tasks were completed.
	  -h  Print this help message.
	EOF
}

main() {
	local option=${2:-}

	local days
	local index
	local today

	case $option in
	[0-9]*)
		[[ $option =~ ^[0-9]+$ ]] || {
			usage
			exit 2
		}
		days=$option
	;;
	-o)
		days=${3:-}
		[[ $days =~ ^[0-9]+$ ]] || {
			usage
			exit 2
		}
	;;
	-h|help|usage)
		usage
		return
	;;
	*)
		usage
		exit 2
	;;
	esac

	today=$(date +%s)
	for ((index = days; index >= 0; index--)); do
		emit_day "$index" "$option" "$today"
	done
}

main "$@"
