#!/usr/bin/env bash

set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \n'

abort() {
	printf '\e[1m\e[38;5;9m✗\e[0m   \e[1m%s\e[0m\n' "$*" >&2
	exit 1
}

succeed() {
	printf '\e[1m\e[38;5;10m✓\e[0m   \e[1m%s\e[0m\n' "$*" >&2
}

warn() {
	printf '\e[1m\e[38;5;11m!\e[0m   \e[1m%s\e[0m\n' "$*" >&2
}

# ------------------------------------------------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------------------------------------------------

verify() {
	local message=$1

	if ! command -v cog &>/dev/null; then
		warn 'Cog required to verify commit message'
		return 0
	fi

	if ! cog verify "$message"; then
		abort 'Commit message does not conform to https://www.conventionalcommits.org/en/v1.0.0'
	fi
}

nitpick() {
	local message=$1

	if ! sed -E 's/^[^:]+: +(.*)$/\1/g' <<<"$message" | grep -Eq '^([a-zığüşöç]|[A-ZİĞÜŞÖÇ]{2,})'; then
		abort 'Description must start with lowercase'
	fi

	if grep -Eq '^refact(:|\()' <<<"$message"; then
		abort 'Do not abbreviate "refactor"'
	fi
}

# ------------------------------------------------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------------------------------------------------

main() {
	local commit_message_file=$1

	local message

	if [[ $(git config hooks.conventional-commits 2>/dev/null || true) != true ]]; then
		exit 0
	fi
	if [[ $(git config hooks.commit-msg 2>/dev/null || true) == false ]]; then
		exit 0
	fi

	message=$(<"$commit_message_file")

	if verify "$message" && nitpick "$message"; then
		succeed 'Commit parse succeeded'
	fi
}

main "$@"
