#!/usr/bin/env bash

set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \n'

readonly FORBIDDEN_BRANCHES='^(master|main|release)$'

# ------------------------------------------------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------------------------------------------------

check() {
	local branch

	branch=$(git rev-parse --abbrev-ref HEAD)

	if [[ $branch =~ $FORBIDDEN_BRANCHES ]]; then
		cat >&2 <<-EOF
			You should not commit directly into $branch branch.
			Please create a new branch from '$branch' and try again.
		EOF

		exit 1
	fi
}

# ------------------------------------------------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------------------------------------------------

main() {
	if [[ $(git for-each-ref --format='%(refname)' refs/heads/ | wc -l) -le 1 ]]; then
		exit 0
	fi

	if [[ $(git config hooks.pre-commit 2>/dev/null || true) == false ]]; then
		exit 0
	fi

	check
}

main "$@"
