#!/usr/bin/env bash

set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \n'

export TODOTXT_VERBOSE=0

# ------------------------------------------------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------------------------------------------------

apply_final_filter() {
	local content=$1

	local filter=${TODOTXT_FINAL_FILTER:-cat}

	# shellcheck disable=SC2086
	echo "$content" | eval $filter
}

configure_simplepv() {
	export TODOTXT_PLAIN=1
	export PRI_X=${NONE:-}
	export PRI_A=${NONE:-}
	export PRI_B=${NONE:-}
	export PRI_C=${NONE:-}
	export DEFAULT=${NONE:-}
	export COLOR_DONE=${NONE:-}

	if [[ $NOWRAP -eq 1 ]]; then
		TODOTXT_FINAL_FILTER=${TODOTXT_FINAL_FILTER:-cat}
	elif command -v fmt &>/dev/null; then
		TODOTXT_FINAL_FILTER="${TODOTXT_FINAL_FILTER:-cat} | fmt -t -w 40"
	fi
}

emit_project() {
	local project=$1
	shift

	local project_list

	project_list=$(_list "$TODO_FILE" "+$project\b" "$@" | sed 's/\ *+[a-zA-Z0-9._\-]*\ */ /g')
	[[ -n $project_list ]] || return

	echo "---  $project  ---"
	apply_final_filter "$project_list"
	[[ ${HOWRUN:-} == simplepv ]] || echo ""
}

list_projects() {
	mapfile -t PROJECTS < <(grep -o '[^ ]*+[^ ]\+' "$TODO_FILE" | grep '^+' | sort -u | sed 's/^+//g')
}

# ------------------------------------------------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------------------------------------------------

usage() {
	cat <<-EOF
	${0##*/} [TERM...]
	  Show todo items containing TERM, grouped by project, and displayed in
	  priority order. If no TERM provided, displays entire todo.txt.
	EOF
}

main() {
	local action=${1:-}
	shift || true

	local project
	local project_list

	declare -a PROJECTS=()
	HOWRUN=${0##*/}
	NOWRAP=0

	if [[ $HOWRUN == simplepv ]]; then
		if [[ ${1:-} == --nowrap ]]; then
			NOWRAP=1
			shift
		fi

		configure_simplepv
	fi

	export TODOTXT_DISABLE_FILTER=1

	if [[ $action == useage || $action == usage ]]; then
		usage
		exit
	fi

	echo "=====  Projects  ====="
	echo ""

	list_projects
	for project in "${PROJECTS[@]}"; do
		emit_project "$project" "$@"
	done

	project_list=$(_list "$TODO_FILE" "$@" | grep -v "+[[:alnum:]]*" || true)
	if [[ -n $project_list ]]; then
		echo "--- Not in projects ---"
		apply_final_filter "$project_list"
	fi
}

main "$@"
