#!/usr/bin/env bash

set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \n'

# ------------------------------------------------------------------------------------------------------------------------
# Commands
# ------------------------------------------------------------------------------------------------------------------------

command.list() {
	"$TODO_FULL_SH" listfile "$TODO_DIR/done.txt"
}

command.revive() {
	local item=$1

	local clean_todo

	getTodo "$item" "$TODO_DIR/done.txt"
	clean_todo=$(echo "${TODO:-}" | sed -E 's/x [0-9]{4}-[0-9]{2}-[0-9]{2} //')
	"$TODO_FULL_SH" add "$clean_todo"
}

# ------------------------------------------------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------------------------------------------------

usage() {
	cat <<-EOF
	revive - Restore tasks from done.txt

	Usage:
	  revive
	      List available todos to revive.

	  revive ITEM
	      Revive specified todo.
	EOF
}

main() {
	local action=${1:-}
	shift || true

	case $action in
	usage)
		usage
		return
	;;
	esac

	case ${1:-} in
	"")
		command.list
	;;
	*)
		if [[ $1 =~ ^[0-9]+$ ]]; then
			command.revive "$1"
			return
		fi

		usage
	;;
	esac
}

main "$@"
