#!/usr/bin/env bash

set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \n'

main() {
	local pager=${PAGER:-cat}

	if command -v bat &>/dev/null; then
		pager=bat
	fi

	[[ ! -f "$TODO_DIR"/README.md ]] || "$pager" "$TODO_DIR"/README.md
}

main "$@"
